language: python
python:
  - "2.7"
script: runestone build && touch build/thinkcspy/.nojekyll &&
  echo 'coding101.devetry.com' > build/thinkcspy/CNAME &&
  for ff in $(find build/thinkcspy/ -name '*.html'); do
      mkdir -p $(sed s/\.html$//g <<< $ff)
      cp $ff $(sed s/\.html$//g <<< $ff)/index.html
  done
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # set in travis-ci.org dashboard
  local_dir: build/thinkcspy/
  on:
    branch: master
